name: test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check
        shell: bash
        run: |
          ./generate_readme/main.sh
          git diff --exit-code -- README.md
